### ISSUE TITLE
Whedon local development/testing

### ISSUE THREAD

**Issue by rgieseke** [openjournals/whedon#17]
@arfon 
Following up on https://github.com/openjournals/joss-reviews/issues/502

Trying to run `whedon` locally I had to

    gem install bibtex-ruby
    gem install dotenv
    gem install thor

after a 

    bundler install

Maybe these are missing from requirements?

This looks ok now:

```
~/sources/whedon (master) [1]> ./bin/whedon 
Commands:
  whedon compile         # Compile the paper and XML metadata
  whedon deposit         # Deposit the metadata with the JOSS application and Crossref
  whedon download        # Download the repo
  whedon help [COMMAND]  # Describe available commands or one specific command
  whedon open            # Open browser for review
  whedon prepare         # Just prepare the PDF
  whedon reviews         # Lists open reviews
  whedon verify          # Check the key values in the review issue
```

How do I now start a local compilation process?

Edit the .env example to point to the repo I want to test?

**Comment by arfon** [comment]
Weird. These dependencies are described here: https://github.com/openjournals/whedon/blob/master/whedon.gemspec#L20-L26

If you modify your `.env` file to look like this:

```
GH_TOKEN=Your GitHub Access Token <- you can get this from here https://help.github.com/articles/creating-a-personal-access-token-for-the-command-line/
DOI_PREFIX = "10.21105"
PAPER_REPOSITORY = "joss-papers"
REVIEW_REPOSITORY = "openjournals/joss-reviews"
JOURNAL_URL = "http://joss.theoj.org"
JOURNAL_NAME = "Journal of Open Source Software"
```

Then you should be able to do:

```
bundle exec whedon download 502 <- where '502' is the review issue number on GitHub
```

then...

```
bundle exec whedon prepare 502 <- this should produce the PDF locally
```

Let me know if you have any problems...

**Comment by rgieseke** [comment]
Alright, with

    bundle exec whedon compile 502

I get a PDF which displays the citation correctly (MAGICC upper-cased).

![image](https://user-images.githubusercontent.com/198537/33944593-f1b67092-e01c-11e7-8dc5-cdd74ae301d5.png)

So it seems to be an issue with the LaTeX version used. 
Where do I find out the TeX version - are these Heroku default images?

**Comment by arfon** [comment]
Hrm, this sounds like an environment issue. When I compile the PDF locally (pulling from `master` at https://github.com/openclimatedata/pymagicc) on my Mac (OSX Sierra 10.12.6) I get the following:

<img width="701" alt="screen shot 2017-12-13 at 9 58 24 am" src="https://user-images.githubusercontent.com/4483/33945152-2fbd7ea2-dfec-11e7-8bbd-c9296322435c.png">

This is the Heroku manifest that is used to build the environment that `@whedon` is using when he tries to compile the papers in the review issues: https://github.com/openjournals/whedon-api/blob/master/app.json

Checking on the Heroku host for the TeX Live version:

```
~ $ tex --version
TeX 3.14159265 (TeX Live 2017)
kpathsea version 6.2.3
Copyright 2017 D.E. Knuth.
There is NO warranty.  Redistribution of this software is
covered by the terms of both the TeX copyright and
the Lesser GNU General Public License.
For more information about these matters, see the file
named COPYING and the TeX source.
Primary author of TeX: D.E. Knuth.```

**Comment by rgieseke** [comment]
On OS X whedon builds nicely without problems.
With Homebrew installed Ruby 2.3:

    gem install bundler

    bundle install

    bundle exec ./bin/whedon reviews
    bundle exec whedon prepare 502
    bundle exec whedon prepare 502

I only had to patch `processor.rb` because I have Pandoc 2 installed which changed some parameters (not sure about how to replace the smart quote option):

```diff
diff --git a/lib/whedon/processor.rb b/lib/whedon/processor.rb
index 86a3b4b..a18cbe5 100644
--- a/lib/whedon/processor.rb
+++ b/lib/whedon/processor.rb
@@ -116,8 +116,8 @@ module Whedon
       -V formatted_doi="#{paper.formatted_doi}" \
       -V citation_author="#{paper.citation_author}" \
       -V paper_title="#{paper.title}" \
-      -S -o #{paper.filename_doi}.pdf -V geometry:margin=1in \
-      --latex-engine=xelatex \
+      -o #{paper.filename_doi}.pdf -V geometry:margin=1in \
+      --pdf-engine=xelatex \
       --filter pandoc-citeproc #{File.basename(paper.paper_path)} \
       --template #{latex_template_path}`
```

However, thinking about the Pandoc version led me to check the `pandoc-citeproc`. I was at 0.10.4. After updating to 0.12.1 the PDF has the correct casing!

I'll try to have a look in the Heroku set-up which `pandoc-citeproc` is used.

In any case it might be necessary to have versions check in `whedon` if more people should use it locally.

**Comment by rgieseke** [comment]
This scholastica build package is a fork of the one currently used (https://github.com/openjournals/whedon-api/blob/master/app.json#L55) 

and points to 
Pandoc 2.0.3 (https://github.com/scholastica/pandoc-buildpack/blob/master/bin/compile#L9)

This version contains `pandoc-citeproc` 0.12.1

@arfon Can you confirm that a later `pandoc-citeproc` version fixes this?

If yes, it might be worth updating to the newer build package, using the patch above.

**Comment by arfon** [comment]
@rgieseke - I've just updated my `pandoc` and `pandoc-citeproc` version locally and it looks like this fixes the issue:

<img width="706" alt="screen shot 2017-12-13 at 4 15 47 pm" src="https://user-images.githubusercontent.com/4483/33962894-16d31da4-e021-11e7-9bfc-94aabc471348.png">

I'll look at upgrading our build environment for Heroku (and @whedon).

**Comment by arfon** [comment]
@rgieseke - it looks like updating the pandoc versions is causing some issues with the deployed version of @whedon over in https://github.com/openjournals/joss-reviews/issues/502

I'll work on a fix but at least for now I can generate the PDF locally that looks better.

**Comment by rgieseke** [comment]
Whoops, posted https://github.com/openjournals/joss/issues/370#issuecomment-351663721 in the wrong issue.

I forgot to download a paper...

```
bundle install --path vendor/bundle
# Adjusting .env with key from GitHub.
bundle exec whedon reviews
bundle exec whedon download 502
bundle exec whedon prepare 502
```

Remaining issue is the Pandoc version. 
Support both? Require Pandoc 2 or Pandoc 1? Any thoughts?
If people should be able to run `whedon` locally this could be a challenge. 

In any case I'll try to summarize what I've learned and send a PR with changes to the Readme.

**Comment by arfon** [comment]
> Support both? Require Pandoc 2 or Pandoc 1? Any thoughts?

I think we can just move ahead and say you need Pandoc 2. 

> In any case I'll try to summarize what I've learned and send a PR with changes to the Readme.

✨ thanks!
