### ISSUE TITLE
inconsistent order of author names in references

### ISSUE THREAD

**Issue by conradsnicta** [openjournals/whedon#2]
Currently the references in the generated papers have an inconsistency. The first author in each reference is listed as Lastname, Firstname, and then following authors are listed as Firstname Lastname.   For example:
Abrahams, David, and Aleksey Gurtovoy

**Comment by pdebuyl** [comment]
Hello,

Any progress on this? I am preparing a submissions and would like the names to be listed properly. Is this an issue with pandoc-citeproc that should be forwarded upstream?

**Comment by pdebuyl** [comment]
Apparently, the behaviour is expected, see https://github.com/jgm/pandoc-citeproc/issues/184

My understanding is that, if we wish to have a "normal" listing of the names we would need to use another csl style.

**Comment by pdebuyl** [comment]
apa.csl is nice :-)

**Comment by conradsnicta** [comment]
I do wonder why the pandoc folks thought that having an inconsistent order for the author names was actually a good idea. Almost nobody uses that citation style, for good reason.

**Comment by arfon** [comment]
/ cc https://github.com/openjournals/joss/issues/400

**Comment by arfon** [comment]
Closing this in favour of https://github.com/openjournals/joss/issues/400
