### ISSUE TITLE
Link to actual PDF instead of GitHub's rendering

### ISSUE THREAD

**Issue by jedbrown** [openjournals/whedon#78]
Upon generating a PDF, Whedon currently links to a URL like

    https://github.com/openjournals/joss-papers/blob/{}.pdf

which is a PNG image of each page and thus does not support search, selection, or clicking links. If Whedon instead linked to

    https://raw.githubusercontent.com/openjournals/joss-papers/{}.pdf

it would use our (browser or native) PDF viewer, which supports all those features. It seems like only folks debugging Whedon would have reason to go to the blob page, and even that may be vanishingly rare. I think we should prefer the better author/reviewer/editor experience of linking directly to the PDF.

**Comment by arfon** [comment]
👏 @jedbrown for fixing this in https://github.com/openjournals/whedon-api/pull/108.
