### ISSUE TITLE
Add line numbers to PDF preview

### ISSUE THREAD

**Issue by JostMigenda** [openjournals/whedon#89]
I’m currently preparing a paper for submission to JOSS and a co-author asked me whether it’s possible to get a paper draft with line numbers for easier editing, similar to the [lineno package](https://texblog.org/2012/02/08/adding-line-numbers-to-documents/) in LaTeX. Would it be possible to add this to `latex.template`?

I guess this should be off by default, with a new command line argument (e.g. [`-V linenumbers="true"`](https://github.com/openjournals/whedon/blob/195e6d124d0fbd5346b87659e695325df9a18334/lib/whedon/processor.rb#L109-L132)) to enable it so it could be used e.g. by the [Whedon paper preview service](https://whedon.theoj.org) without affecting other usage of that template.

**Comment by arfon** [comment]
Thanks for the suggestion! This was fixed in https://github.com/openjournals/whedon/commit/a0b7af7c4770ff988a4570b1ceea09d28d489128

![Uploading Screen Shot 2020-12-15 at 16.18.50.png…]()
