### ISSUE TITLE
Problems with whedon automatic author reminder

### ISSUE THREAD

**Issue by kakiac** [openjournals/whedon#91]
Hi, 

Hope this is the correct space to report this - have a look at https://github.com/openjournals/joss-reviews/issues/2708#issuecomment-736540540

I am trying to set a reminder to the authors for mid January, I tried this command: 

`@whedon remind @yson in six weeks`

to which whedon reports 

`@yson doesn't seem to be a reviewer or author for this submission.`

which is not correct, as `@yson` is the author of that submission.

Any suggestions as to what I might be doing wrong here and how I could set the reminders?

**Comment by xuanxu** [comment]
It looks like you want a reminder for `@ysohn` not `@yson` :)

**Comment by kakiac** [comment]
AAHrgh 😄  I hate it when machines get it always right! Thanks @xuanxu!
